version: "3.9"

services:
  backend:
    build: .
    command: uvicorn routes:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./credit_approval.db
    depends_on:
      - redis

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"